In [1]:
# drive mount. colab에 내 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# import_ipynb module 설치
!pip install import_ipynb

# import를 위한 경로이동
%cd /content/drive/MyDrive/team_malmungchi/colab/speaker_verification/code
!ls

Mounted at /content/drive
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 12.9 MB/s 
/content/drive/.shortcut-targets-by-id/1rEYIox5uYM9uP2spDttCYCqtt2GvSbn1/team_malmungchi/colab/speaker_verification/code
batcher.ipynb		 convert.ipynb	     network.ipynb
call_development1.ipynb  development.ipynb   preprocess.ipynb
call_development2.ipynb  eval_metrics.ipynb  test_eer.ipynb
call_development3.ipynb  evaluation.ipynb    utils.ipynb
call_tflite.ipynb	 fitter.ipynb
constants.ipynb		 loss.ipynb


In [2]:
import os
import sys
import tensorflow as tf
import numpy as np
import time

In [3]:
x_test = [[0]*128 for i in range(128)]
x_test = np.array(x_test, dtype=np.float32)
x_test = np.expand_dims(x_test, axis=-1)
x_test = np.expand_dims(x_test, axis=0)

interpreter = tf.lite.Interpreter('../model/tiny_CRNN-naive_batcher-cross_entropy.tflite')
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_shape = input_details[0]['shape']
print(input_shape)
interpreter.set_tensor(input_details[0]['index'], x_test)

start = time.time()
interpreter.invoke()
end = time.time()
print(end-start)

output_data = interpreter.get_tensor(output_details[0]['index'])

print(output_data)

[  1 128 128   1]
0.06396007537841797
[[-1.8406881  -3.6865506  -2.6482294   1.0790334  -0.28861842  1.9417305
  -4.780822   -3.216423   -1.0630257  -1.9918188  -0.50918585  0.521637
  -0.615194    2.8731549  -0.1972641   1.4735705   1.1957728  -1.9563161
  -1.581346   -1.6088082  -1.3596247   0.19646232  0.09262091  0.58644277
  -1.4567509  -0.51472425 -1.4242201  -1.7124411   4.556734   -0.01183098
   0.9873472  -3.7199023   2.7240763  -1.2628505  -0.19727775 -0.36482093
  -0.46956345 -0.01350068 -0.13903387 -2.8533864   1.224552   -0.7670122
  -0.22731522  0.09585034 -2.7339056   1.1364944  -1.573949   -1.384914
   2.9313142  -0.8441622   0.80065936 -0.3461822   3.1796784   4.119818
  -1.801828   -2.3387609   0.1818267   1.1516062   1.8199964  -1.4371899
   1.054549    1.1323448  -1.2621052  -0.0681982  -2.1199615   0.9740005
  -0.94682926 -0.22533503 -1.1870557   2.9411602  -2.2183173   0.84110975
   0.8704497   0.43599182 -1.2899566  -0.8056107   0.6274524   3.0187328
   2.691993 

In [4]:
print(x_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]]
